server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:mappers/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.chryl: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: chryl
    druid:
      initial-size: 5 #\u8FDE\u63A5\u6C60\u521D\u59CB\u5316\u5927\u5C0F
      min-idle: 10 #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      max-active: 20 #\u6700\u5927\u8FDE\u63A5\u6570
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #\u4E0D\u7EDF\u8BA1\u8FD9\u4E9B\u8BF7\u6C42\u6570\u636E
      stat-view-servlet: #\u8BBF\u95EE\u76D1\u63A7\u7F51\u9875\u7684\u767B\u5F55\u7528\u6237\u540D\u548C\u5BC6\u7801
        login-username: druid
        login-password: druid
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300